prefixes:
  normal: PREFIX FOR NORMAL COMMANDS
  admin: PREFIX FOR ADMIN COMMANDS
  master: PREFIX FOR MASTER COMMANDS

discord:
  default_role: DEFAULT DISCORD ROLE
  subscriber_role: DISCORD SUBSCRIBER ROLE
  twitch_updates_chat: CHAT TO SEND WHEN LILPOTATE IS LIVE
  twitch_discord_chat: CHAT TO SEND TWITCH CHAT
  bot_owner_id: DISCORD ID OF THE BOT OWNER
  admin_log_chat: ADMIN LOG CHAT
  admin_roles:
    - DISCORD ADMIN ROLE 
  owners:
    - DISCORD OWNER ID

twitch:
  username: BOTS TWITCH USERNAME
  channels: 
    - TWITCH CHANNEL NAME
  admins:
    - name: TWITCH USERNAME
      id: TWITCH USER ID
  icons:
    no_badge: 
    sub_gifter: 
    moderator: 
    subscriber: 
    partner: 
    founder: 
    premium: 
    bits: 

extra:
  default_steam_id: STEAM ID 64
